spring.application.name=ZENA
# Dados de conexão com o Oracle
# spring.datasource.url=jdbc:oracle:thin:@//oracle.fiap.com.br:1521/orcl
# spring.datasource.username=rm555345
# spring.datasource.password=240304
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações JPA
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
# spring.jpa.show-sql=true
# spring.application.name=ZENA

#Rodando nuvem (render):
# Dados de conexão com o Oracle
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
