// <auto-generated />
using AbrigoApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace AbrigoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250604221340_RemovendoAtivoPorEnquanto")]
    partial class RemovendoAtivoPorEnquanto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AbrigoApi.Domain.Abrigo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("ID");

                    b.Property<byte>("Ativo")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ATIVO");

                    b.Property<int>("Capacidade")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPACIDADE");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("ENDERECO");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("NUMBER(9,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("OcupacaoAtual")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("OCUPACAO_ATUAL");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id")
                        .HasName("PK_ABRIGOS");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ABRIGOS", (string)null);
                });

            modelBuilder.Entity("AbrigoApi.Domain.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("VARCHAR2(255)")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("ROLE");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("USERNAME");

                    b.HasKey("Id")
                        .HasName("PK_USUARIOS");

                    b.ToTable("USUARIOS", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("AbrigoApi.Domain.Abrigo", b =>
                {
                    b.HasOne("AbrigoApi.Domain.Usuario", "Usuario")
                        .WithMany("Abrigos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ABRIGOS_USUARIOS_USUARIOID");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AbrigoApi.Domain.Usuario", b =>
                {
                    b.Navigation("Abrigos");
                });
#pragma warning restore 612, 618
        }
    }
}
